name: journal_club_uab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - pip
  - pytest
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - traits
  - pip:
    - nbval
    - nibabel
    - nilearn
    - nipy
    - nipype
